/* Our goal is to explore our dataset and gather some information before digging deeper into the insights and KPIs */

SELECT * FROM tableRetail;

SELECT COUNT(*) FROM TABLERETAIL;

SELECT COUNT(DISTINCT CUSTOMER_ID) FROM TABLERETAIL;

SELECT COUNT(DISTINCT STOCKCODE) FROM TABLERETAIL;

SELECT DISTINCT COUNTRY FROM TABLERETAIL;

SELECT MIN(INVOICEDATE), MAX(INVOICEDATE) FROM TABLERETAIL;

SELECT COUNT(DISTINCT INVOICE) FROM TABLERETAIL;